= Review "APM - Agiles Projektmanagement"
Daniel Grycman <danielgrycman@icloud.com>
:icons: font

NOTE: I review books in the language they are written in.

[.lead]
Der Autor und seine Co-Autoren versprechen auf dem Buchtitel die erfolgreiche Steuerung von anspruchsvollen Softwareprojekten beim Einsatz der APM-Methodik.

Bereits im Jahr 2007 ist das erste Buch zu APM (Agiles Projektmanagement) erschienen und etablierte sich bald zu einem Standardwerk im Bereich agiler Methoden im deutschsprachigen Raum. In diesem Buch hatte Uwe Vigenschow bereits als Co-Autor mitgewirkt und nun ist unter seiner Federführung eine neue Ausgabe entstanden. Es ist hierbei zu beachten, dass das Buch in Gänze neu geschrieben wurde und dies unter Berücktsichtigung der gewonnenen Erfahrung im Umgang mit agilen Prinzipen geschehen ist. Ebenso ist anzumerken, dass auch die Co-Autoren Andrea Grass, Alexandra Augstin und Michael Hoffmann tief in der Materie verwurzelt sind.

Der Autor führt den interessierten Leser über fünf Teile mit insgesamt 23 Kapiteln in das Thema der agilen Methodik ein. Im ersten Teil gibt Vigenschow eine Einführung in die Konzepte von Agilität und dem Projektmanagement-Framework APM. Der zweite Teil beschäftigt sich mit dem Aufsetzen eines agilen Projekts. Im nächsten Teil widmet sich der Autor dem Einfluß von Agilität auf die Architektur von Software. Der vierte Teil beschäftigt sich der iterativen Heransgehenweise von agiler Softwareentwicklung. Ebenso legt Vigenschow Wert darauf, dass sich der Leser mit dem Rollenverständnis der Beteiligten auseinandersetzt. Der letzte Teil stellt die Anwendung der Methodik im Rahmen von Großprojekten dar und beschreibt zusätzlich die Einführung in Unternehmen selbst.

Der geneigte Leser bemerkt beim Lesen des Buches, dass Uwe Vigenschow über eine langjährige Erfahrung als Trainer verfügt. Dies spiegelt sich sowohl in dem didaktischen Aufbau der einzelnen Teile und Kapitel wider, als auch in der sprachlichen Ausgestaltung des gesamten Werkes. Durch den sehr detailierten Index eignet sich das Buch auch als Nachschlagewerk. Das beiliegende Poster bietet dem Leser die Möglichkeit der Grundlagen .

Das Buch "APM - Agiles Projektmanagement" ist jedem zu empfehlen, der sich in die Methodiken der agilen Softwareentwicklung einarbeiten möchte. Ebenso bietet sich dieses Werk auch allen Praktikern als gutes Nachschlagewerk an.


[sidebar]
[.text-right]
****
[cols="2*"]
|===
.7+^.^| pass:[<a rel="nofollow" href="http://www.amazon.de/gp/product/3864902118/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=3864902118&linkCode=as2&tag=danigryc-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=3864902118&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=danigryc-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=danigryc-21&l=as2&o=3&a=3864902118" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />]
| *Autor:*  Uwe Vigenschow, unter Mitarbeit von Andrea Grass, Alexandra Augstin und Michael Hoffmann

| *Titel:*  APM - Agiles Projektmanagement

| *Auflage:*  1. Auflage 2015

| *Verlag:*  dpunkt.verlag, Heidelberg

| *Umfang:*  451 Seiten

| *Preis:*  44,90 Euro, _eBook (downloadbar) nicht im Preis enthalten_

| *ISBN:* 978-3-86490-211-6

|===
****

[.text-center]
_Diese Rezension wird ebenfalls im Magazin Java Aktuell Ausgabe 04/2015 veröffentlicht._