= Review "InDesign automatisieren - Keine Angst vor Skripting, GREP {amp} Co."
Daniel Grycman <danielgrycman@icloud.com>
:icons: font

NOTE: I review books in the language they are written in.

[.lead]
"GREP und Skripting sind kein Hexenwerk."

Mit der zweiten Auflage stärkt Gregor Fellenz die Position seines Buches als das deutschsprachige Referenzwerk für die Automatisierung von InDesign.

Das Buch ist in drei Teile unterteilt. Im ersten Teil wird der Einstieg in die Thematik der Automatisierung gelegt. Der zweite Teil führt in die InDesign-Programmierung mit JavaScript ein. Im dritten und letzten Teil zeigt der Autor wie Automatisierung konkret in der Praxis funktionieren kann. Der Autor verwendet für seine Ausführungen einen sehr angenehmen Sprachstil, so dass es dem Leser leicht fällt den Ausführungen zu folgen. Sehr angenehm fallen auch die vielen Beispielskripte und Angaben zu Quellen im Internet auf. Die erwähnten Skripten liegen ebenfalls als Repository bei github vor, um direkt mit den Skripten ohne Abtippen arbeiten zu können.

Das Buch ist allen Interessierten zu empfehlen, die sich mit Automatisierung und Skripten rund um InDesign beschäftigen.

[sidebar]
[.text-right]
****
[cols="2*"]
|===
.7+^.^| pass:[<a rel="nofollow" href="http://www.amazon.de/gp/product/3864902355/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=3864902355&linkCode=as2&tag=danigryc-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=3864902355&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=danigryc-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=danigryc-21&l=as2&o=3&a=3864902355" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />]
| *Autor:* Gregor Fellenz

| *Titel:* InDesign automatisieren - Keine Angst vor Skripting, GREP & Co.

| *Auflage:* 2., aktualisierte und erweitere Auflage

| *Verlag:*  dpunkt.verlag

| *Umfang:*  382 Seiten

| *Preis:*  36,90 Euro

| *ISBN:* 978-3-86490-235-2

|===
****
