= Review "Einstieg in XML - Grundlagen, Praxis, Referenz"
Daniel Grycman <danielgrycman@icloud.com>
:icons: font

NOTE: I review books in the language they are written in.

[.lead]
"XML lernen und effizient einsetzen!" verspricht der Rheinwerk Verlag auf dem Buchrücken zur achten aktualisierten Auflage.

Die meisten fragen sich, warum ein Einsteigerbuch zu XML bereits in der achten Auflage erscheint. Das Datenformat XML ist überall zu finden, ob bei Office-Anwendungen, im Dynamic Publishing oder als ein reines Austauschformat. Somit hat dieses Buch seinen berechtigten Platz, um XML Wissen in gebündelter Form zu vermitteln.

Die aktualisierte achte Auflage ist in 15 Kapiteln unterteilt. Den Anfang bilden Grundlagen zur Syntax und die Möglichkeiten zur Prüfung der Gültigkeit anhand von DTD oder XML-Schema. Auf die Navigation innerhalb eines XML-Dokuments geht der Autor im nachfolgenden Kapitel ein. Weiter geht die Lesereise durch die Varianten der formatierten Ausgabe von XML, sowohl mit CSS als auch mittels XSLT. Der Formatierung mit XSL widmet Vonhoegen ein einiges sehr detailliertes Kapitel. Der Einsatz von Abfragen mit XQuery und die Verwendung von Programmierschnittstellen für XML kommen auch nicht zu kurz.  Den Abschluss bilden konkrete Beispiele zur Anwendung von Datenformaten, die auf XML basieren wie Webdienste, Office-Anwendungen aus dem Microsoft-Kosmos, EPUB und HTML5.

Im Großen und Ganzen vermittelt dieses Einsteigerwerk dem Leser einen umfassenden Überblick über XML als Programmiersprache und ebenso über verschiedene Einsatzmöglichkeiten. Dieses Buch ist aber auch XML-Profis als Nachschlagewerk uneingeschränkt zu empfehlen.

[sidebar]
[.text-right]
****
[cols="2*"]
|===
.7+^.^| pass:[<a rel="nofollow" href="http://www.amazon.de/gp/product/3836237989/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=3836237989&linkCode=as2&tag=danigryc-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=3836237989&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=danigryc-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=danigryc-21&l=as2&o=3&a=3836237989" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />]
| *Autor:* Helmut Vonhoegen

| *Titel:* Einstieg in XML - Grundlagen, Praxis, Referenz

| *Auflage:* 8., aktualisierte Auflage

| *Verlag:* Rheinwerk Verlag

| *Umfang:* 615 Seiten

| *Preis:* 39,90 Euro

| *ISBN:* 978-3-8362-3798-7

|===
****
