= Review "Java ist auch eine Insel - Einführung, Ausbildung, Praxis"
Daniel Grycman <danielgrycman@icloud.com>
:icons: font


NOTE: I review books in the language they are written in.

[.lead]
Nun ist schon die zwölfte aktualisierte Auflage des deutschsprachigen Standardwerks "Java ist auch eine Insel" von Christian Ullenboom im Rheinwerk Verlag erschienen. Wie der Autor im Vorwort schreibt, sind hauptsächlich Fehlerkorrekturen vorgenommen worden. Als einzige Neuerung wurde das bisherige zwölfte Kapitel aufgespalten. Im neuen dreizehnten Kapitel geht Ullenboom auf die kommende Modularisierung in Java 9 ein.

Das Buch besticht durch sein ausführliches Inhaltsverzeichnis, welches die Inhalte in 23 Kapitel unterteilt. Im Vorwort bietet Christian Ullenboom eine mögliche Lernstrategie zum Lesen und Lernen an. Er bezieht sich hierbei auf die PQ4R-Methode. Diese Methode soll einem Anfänger im Bereich der Java-Programmierung den Einstieg und den Wissenerwerb erleichtern.
In den ersten 13 Kapiteln wird dem Leser Java als Programmiersprache näher gebracht. Diese ersten 13 Kapitel stellen zugleich auch den ersten Teil des Buches dar. Im zweiten Teil beschäftigt sich der Autor mit auf grundlegenden APIs. Allen Kapitel ist gemein, dass an deren Ende ein Abschnitt mit dem Titel "Zum Weiterlesen" enthalten ist. Dies soll dem Leser die Möglichkeit geben, sich mit einem bestimmten Thema weiter auseinanderzusetzen. Den Abschluß des Werkes bilden eine ausführliche Übersicht über die, in Java 8 enthaltenen, Pakete und einen Index.
Die neuste Auflage der "Insel" stellt auch eine absolute Kaufempfehlung für Java-Neulinge dar. Das Buch präsentiert auf eine verständliche Art und Weise die notwendigen Techniken zur Java-Programmierung und gibt auch praxisorientierte Informationen an den geneigten Leser weiter.


[sidebar]
[.text-right]
****
[cols="2*"]
|===
.7+^.^| pass:[<a rel="nofollow" href="http://www.amazon.de/gp/product/3836241196/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=3836241196&linkCode=as2&tag=danigryc-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=3836241196&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=danigryc-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=danigryc-21&l=as2&o=3&a=3836241196" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
]
| *Autor:* Christian Ullenboom

| *Titel:* Java ist auch eine Insel - Einführung, Ausbildung, Praxis

| *Auflage:* 12. Auflage 2016

| *Verlag:* Rheinwerk Verlag

| *Umfang:* 1312 Seiten

| *Preis:* 49,90 Euro

| *ISBN:* 978-3-8362-4119-9

|===
****

[.text-center]
_Diese Rezension wird ebenfalls im Magazin Java Aktuell Ausgabe 03/2016 veröffentlicht._