= Review "Oracle PL/SQL - Das umfassende Handbuch"
Daniel Grycman <danielgrycman@icloud.com>
:icons: font

NOTE: I review books in the language they are written in.

[.lead]
Auf knapp 1000 Seiten in der zweiten aktualisierten und erweiterten Auflage präsentiert Jürgen Sieben sein Wissen über PL/SQL-Datenbankprogrammierung.

Der Autor hat mit seinem Werk eine ganz bestimmte Zielgruppe im Auge: Entwickler, die sowohl über Kenntnisse in mindestens einer Programmiersprache verfügen als auch die Grundlagen von SQL beherrschen.

Das Buch ist in vier Teile gegliedert. Der erste Teil beschäftigt sich mit den "Grundlagen". Hierbei erläutert den Aufbau der Oracle-Datenbank. Der nächste Teil gibt eine schnelle Einführung in die Programmiersprache "PL/SQL". Im dritten Teil widmet sich der Autor verschiedenen Einsatzgebieten von PL/SQL: Umgang mit LOB- und XML-Datentypen, Einsatz von Objektorientierung in der Datenbank oder der Erweiterung von SQL. Den Abschluss im vierten und letzten Teil bilden "Workshops" mit praktischen Übungen für Leser, die das Gelesende weiter vertiefen wollen.

Dieses Werk ist für alle Anwendungsentwickler, die Daten mit einer Oracle Datenbank austauschen, eine lesenswerte Lektüre.
[sidebar]
[.text-right]
****
[cols="2*"]
|===
.7+^.^| pass:[<a rel="nofollow" href="http://www.amazon.de/gp/product/3836224976/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=3836224976&linkCode=as2&tag=danigryc-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=3836224976&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=danigryc-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=danigryc-21&l=as2&o=3&a=3836224976" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
]
| *Autor:* Jürgen Sieben

| *Titel:* Oracle PL/SQL - Das umfassende Handbuch

| *Auflage:* 2., erweiterte und aktualisierte Auflage

| *Verlag:* Rheinwerk Verlag

| *Umfang:* 991 Seiten

| *Preis:* 69,90 Euro, _eBook (downloadbar) im Preis enthalten_

| *ISBN:* 978-3-8362-2497-0

|===
****
